[general]
database = "postgres"

[postgres]
postgres_user = "rdmo"
postgres_password = "admin"
postgres_db = "rdmo"
postgres_host = "postgres"
postgres_port = 5432

[rdmo]
api_dev_key = "58114e78e6c3488247148a3e5c9e6fa462a9e4c9"
install_source = "/home/rdmo/rdmo"
rdmo_source_mp = "/home/rdmo/rdmo"
rdmo_app_mp = "/home/rdmo/rdmo-app"

[repos]
rdmo = "https://github.com/rdmorganiser/rdmo.git"
rdmo_catalog = "https://github.com/rdmorganiser/rdmo-catalog.git"
