rdmo_dockerfile = "alpine"

[folders]
rdmo_source = "${HOME}/rolling/aip/github/rdmo"
rdmo_app = "${HOME}/rolling/aip/github/rdmo-app"
rdmo_plugins = "${HOME}/rolling/aip/github/rdmo-plugins"
shed = "${HOME}/tools/shed"
mybins = "${HOME}/tools/mybins"

[mountpoints]
rdmo_source = "/home/rdmo/rdmo"
rdmo_app = "/home/rdmo/app"
rdmo_plugins = "/home/rdmo/rdmo-plugins"
shed = "/vol/shed"
mybins = "/vol/mybins"

[repos]
rdmo = "https://github.com/rdmorganiser/rdmo.git"
rdmo_catalog = "https://github.com/rdmorganiser/rdmo-catalog.git"

[general]
database = "postgres"

[postgres]
postgres_user = "rdmo"
postgres_password = "admin"
postgres_db = "rdmo"
postgres_host = "postgres"
postgres_port = 5432
api_dev_key = "58114e78e6c3488247148a3e5c9e6fa462a9e4c9"
install_source = "/home/rdmo/rdmo"
