version: "3.6"

services:
    postgres:
        # image: postgres
        build:
            context: ./postgres
        container_name: postgres
        ports:
            - "6543:5432"
        env_file:
            - 'variables.env'

    rdmo:
        build:
            context: ./rdmo
        container_name: rdmo
        depends_on:
            - postgres
        ports:
            - "8280:8080"
        volumes:
            - rdmosrc:<RDMO_SOURCE_MP>
            - rdmoapp:/home/rdmo/rdmo-app
            - shed:/tools/shed:ro
            - mybins:/tools/mybins:ro
        env_file:
            - 'variables.env'

volumes:
    rdmosrc:
        driver_opts:
            type: none
            device: <HOME>/rolling/aip/github/rdmo
            o: bind
    rdmoapp:
        driver_opts:
            type: none
            device: <HOME>/rolling/aip/github/rdmo-app
            o: bind
    shed:
        driver_opts:
            type: none
            device: <HOME>/tools/shed
            o: bind
    mybins:
        driver_opts:
            type: none
            device: <HOME>/tools/mybins
            o: bind
