version: "3.6"


volumes:
    rdmosrc:
        driver_opts:
            type: none
            device: /home/olaf/aip/github/rdmo
            o: bind
    rdmoapp:
        driver_opts:
            type: none
            device: /srv/rdmo/rdmo-app
            o: bind
    rdmostatic:
        driver_opts:
            type: none
            device: /srv/rdmo/rdmo-app
            o: bind


services:
    postgres:
        image: postgres
        container_name: postgres
        env_file:
            - 'variables.env'

    nginx:
        build:
            context: ./nginx
        container_name: nginx
        ports:
            - "8280:8280"
        volumes:
            - rdmosrc:/src/rdmo
            - rdmoapp:/src/rdmo-app
        env_file:
            - 'variables.env'
        depends_on:
            - rdmo

    rdmo:
        build:
            context: ./rdmo
        container_name: rdmo
        depends_on:
            - postgres
        ports:
            - "8281:80"
        volumes:
            - rdmosrc:/src/rdmo
            - rdmoapp:/src/rdmo-app
        env_file:
            - 'variables.env'
