FROM debian:latest

ENV USER=rdmo
ENV UID=1000
ENV GNAME=rdmo
ENV GID=1000
ENV HOME=/home/rdmo

ENV PATH="${PATH}:${HOME}/.local/bin:${HOME}/sh:/vol/tools/shed:/vol/tools/mybins"

RUN apt update -y

# install python3
RUN apt install -y python3 python3-dev python3-pip \
 && pip3 install pytest

# and build dependencies
RUN apt install -y \
    build-essential \
    git \
    libxml2-dev \
    libxslt-dev \
    zlib1g-dev \
    pandoc \
    procps \
    sudo

# postgres and its dependencies
RUN apt install -y \
    python-psycopg2 \
    libpq-dev \
    postgresql \
    postgresql-client \
 && pip3 install psycopg2

# pip upgrade and rdmo installation
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade wheel
RUN pip3 install --upgrade setuptools

RUN rm -f /usr/bin/python \
&& ln -s /usr/bin/python3 /usr/bin/python

# note: texlive-xetex 1500MB, required otherwise tests will break
RUN apt install -y texlive-xetex

COPY ./rootfs /

RUN groupadd -g "${GID}" "${GNAME}" \
 && useradd -m -s /bin/false -g "${GNAME}" -u "${UID}" "${USER}" \
 && adduser "${USER}" "sudo" \
 && chown -R "${USER}:${GID}" "${HOME}" \
 && echo "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd \
 && chmod 777 /var/log

HEALTHCHECK --timeout=5s --interval=600s --retries=3 \
   CMD httpstat http://localhost:8080 || pkill -9 python

USER "${USER}"
CMD ["/drun.sh"]
