FROM rdmo-dev-rdmo:latest

env NVM_DIR="${HOME}/.nvm"

USER root
RUN apk add --no-cache --update nodejs
RUN apk add --no-cache --update npm

USER "${USER}"
WORKDIR ${HOME}
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash

COPY rootfs/home/usr/sh/make-release.sh /usr/bin/
WORKDIR ${HOME}/rdmo

CMD ["make-release.sh"]
