FROM debian:9

RUN apt update -y \
    && apt install -y \
    nginx \
    curl

RUN useradd -ms /bin/false nginx \
    && usermod -aG nginx nginx

COPY ./rootfs /
RUN chmod u+x /*.sh

CMD ["/drun.sh"]
