FROM debian:9

ENV PATH="${PATH}:/opt:/tools/shed:/tools/mybins"

RUN apt update -y

# install python3
RUN apt install -y \
    python3 \
    python3-dev \
    python3-pip

# and build dependencies
RUN apt install -y \
    build-essential \
    git \
    libxml2-dev \
    libxslt-dev \
    zlib1g-dev \
    pandoc \
    procps \
    curl \
    vim

# postgres and its dependencies
RUN apt install -y \
    python-psycopg2 \
    libpq-dev \
    postgresql \
    postgresql-client

# python tooling
RUN pip3 install \
    autoflake \
    isort \
    pytest \
    vulture

# pip upgrade and rdmo installation
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade wheel
RUN pip3 install --upgrade setuptools

# postgres python dependency
RUN pip3 install psycopg2

# note: texlive-xetex 1500MB, required otherwise tests will break
RUN apt install -y texlive-xetex

# copy rootfs
COPY ./rootfs /
RUN chmod u+x /*.sh

# check
HEALTHCHECK --timeout=5s --interval=5s --retries=3 \
   CMD curl -f http://localhost:8080 || exit 1

# running everything
CMD ["/drun.sh"]
