FROM debian:9

RUN apt update -y


# install python3 and build dependencies
RUN apt install -y \
    python3 \
    python3-dev \
    python3-pip \
    build-essential \
    git \
    libxml2-dev \
    libxslt-dev \
    zlib1g-dev \
    pandoc \
    procps \
    curl \
    vim

# symbolic links
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# pip upgrade and rdmo installation
RUN pip install --upgrade pip
RUN pip install --upgrade wheel
RUN pip install --upgrade setuptools

# postgres python dependency
RUN pip install psycopg2

# note: texlive-xetex is for pdf export only 1500MB, really!??
# RUN apt install -y texlive-xetex

# copy rootfs
COPY ./rootfs /
RUN chmod u+x /*.sh

# check
HEALTHCHECK --timeout=5s --interval=5s --retries=3 \
   CMD curl -f http://localhost:80 || exit 1

# running everything
CMD ["/drun.sh"]
