#!/bin/bash

host="127.0.0.1"
arg2="${2}"

function check_second_arg(){
    if [[ -z "${arg2}" ]]; then
        echo -e "\nThe following commands are available:"
        echo -e "  - push [DB_FILE]"
        echo -e "  - pull or dump [DB_NAME]"
        echo -e "  - empty_table [TABLE_NAME]"
        echo -e "\nBoth need a second arg. Either the file to inject or the one to write into.\n"
        exit
    fi
}

cmdargs="-h ${host} -p ${POSTGRES_PORT} -U ${POSTGRES_USER} ${POSTGRES_DB}"
cmdpsql="psql ${cmdargs}"
cmddump="pgdump ${cmdargs}"

if [[ "${1}" == "list" ]]; then
    cmd="${cmdpsql} -c \"\\dt\""
fi

if [[ "${1}" == "push" ]]; then
    check_second_arg
    dropdb -U ${POSTGRES_USER} ${POSTGRES_DB}
    createdb -U ${POSTGRES_USER} ${POSTGRES_DB}
    cmd="${cmdbase} -f \"${arg2}\""
fi

if [[ "${1}" =~ (pull|dump) ]]; then
    check_second_arg
    cmd="${cmddump} -f \"${arg2}\""
fi

if [[ "${1}" == "empty_table" ]]; then
    check_second_arg
    cmd="${cmdpsql} -c \"delete from ${arg2}\""
fi

echo "${cmd}"
eval "${cmd}"
