FROM ubuntu:16.04

ENV RDMODIR /srv/rdmo
ENV RDMOAPPDIR /srv/rdmo/rdmo-app

RUN apt update -y

# install python3 and build dependencies
RUN apt install -y \
   python3 \
   python3-dev \
   python3-pip \
   build-essential \
   git \
   libxml2-dev \
   libxslt-dev \
   zlib1g-dev \
   pandoc \
   curl \
   vim \
   mc

# symbolic links
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# pip upgrade and rdmo installation
RUN pip install --upgrade pip
RUN pip install --upgrade wheel
RUN pip install --upgrade setuptools

# apache install and settings
RUN apt install -y \
  apache2 \
  libapache2-mod-wsgi-py3
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE=/var/run/apache2.pid
ENV APACHE_LOCK_DIR=/var/lock/apache2

# create and change user
RUN useradd -m -d ${RDMODIR} -s /bin/bash rdmo
RUN chown -R rdmo:rdmo ${RDMODIR}

# copy, copy, copy
COPY ./generic /
COPY ./specific/apache2 /

# rename config file to make sure it gets copied correctly later by docker run
RUN mv /tmp/local-template-sqlite.py  /tmp/local-template.py

# check and run
HEALTHCHECK --timeout=5s --interval=5s --retries=3 \
   CMD curl -f http://localhost:80 || exit 1

CMD ["/drun.sh"]
